services:
  postgres:
    image: postgres:alpine
    container_name: postgresgemz
    restart: always
    shm_size: 256mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gemz
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
    healthcheck:
      test: [ CMD-SHELL, pg_isready -U postgres ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - gemz-network

  redis:
    image: redis:alpine
    container_name: gemz_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - gemz-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemz-app
    ports:
      - "3000:3002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - gemz-network

networks:
  gemz-network:
    driver: bridge
